AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/SpaceInsideStringInterpolation:
  EnforcedStyle: space

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: compact

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Naming/RescuedExceptionsVariableName:
  PreferredName: exception

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/AsciiComments:
  Enabled: false

Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
    inject: 'inject'

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Style/FrozenStringLiteralComment:
  SupportedStyles:
    - always

Style/HashEachMethods:
  Enabled: true

Style/HashAsLastArrayItem:
  EnforcedStyle: no_braces

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/RaiseArgs:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true

Style/SingleLineBlockParams:
  Enabled: false

Style/WordArray:
  Enabled: false